### ISSUE TITLE
35 Refactor Day Conversion in Create Use Cases

### ISSUE THREAD

**Issue by DanielLivshits** [CSC207-2022F-UofT/course-project-blue-guppies#55]
An issue that should've been pointed out before but went unnoticed: Converting from a String input for a day to an integer is the responsibility of the Controller, not the Input Data. 
The process of converting a String input for a day to an int should happen in the UseCaseController, and the UseCaseInputData should already have DayIndex as an int.

**Comment by Fard-Faru** [comment]
Ill take care of this for CreateEvent and CreateTask Use Case
